Refactor review edit cell to use ReactQuery mutation instead
tableflowhq/tableflow pull request #136
Opened 2023-10-02 16:15 UTC by civan

Resolves TF-243

2023-10-02 18:02 UTC, ciminelli requested changes
The structure for the hook looks good, just need to update the logic and fix the branch (I think this was branched off of an old version of main)

2023-10-02 18:02 UTC, ciminelli commented on importer-ui/src/features/review/index.tsx
> +  }, [dataCellEdited, cellValueChangedEvent]);
Can you refactor this so the logic is the same as before? Looks like some things have changed around and code is missing. Specifically, around error handling and the logic around updating the row node data.

2023-10-02 18:02 UTC, ciminelli commented on importer-ui/usePostReviewEditCell.ts
> +}
Duplicate function?

2023-10-02 18:02 UTC, ciminelli commented on importer-ui/src/features/review/index.tsx
> +    // TODO: Works only after clicking filter options
I think you might have branched off of old code. I don't think this function exists in main.

2023-10-04 00:04 UTC, civan commented on importer-ui/src/features/review/index.tsx
> +  }, [dataCellEdited, cellValueChangedEvent]);
right! sorry about that, it looked like the branch was outdated, let me know what you think!

2023-10-04 00:11 UTC, civan commented on importer-ui/usePostReviewEditCell.ts
> +}
good catch! done!

2023-10-06 20:56 UTC, ciminelli commented on importer-ui/src/features/review/index.tsx
> +  }, [dataCellEdited, cellValueChangedEvent]);
Testing the edit functionality it looks like it's not working, I think the logic is different still. I'll take a closer look.

2023-10-06 20:57 UTC, ciminelli commented on importer-ui/src/features/review/index.tsx
> +  }, [dataCellEdited, cellValueChangedEvent]);
https://github.com/tableflowhq/tableflow/assets/11033848/027d4863-e404-437b-9050-b5735732753c

2023-10-06 21:01 UTC, ciminelli commented on importer-ui/src/features/review/index.tsx
> +  }, [dataCellEdited, cellValueChangedEvent]);
I would say let's leave this for now since it's now high-priority, but when we get back to it I think you could start by copying the exact code from the existing post response and modify from there. We'll need to make sure the errors for the row node, api request, errors not existing, etc. all work the same as it does currently.

2023-10-11 20:29 UTC, ciminelli commented
Closing out for now, we can revisit soon.

2023-10-11 20:29 UTC, closed without merging